#!/bin/bash
# Copyright (c) 2015 Jeremy Miller
# All rights reserved.
#
# Author: Jeremy Miller, 2015
#
# /etc/init.d/deluge
# chkconfig: 345 70 30

. /etc/init.d/functions

RETVAL=0
prog="deluge"
LOCKFILE=/var/lock/subsys/$prog

start() {
        echo -n "Starting $prog: "
        deluged && deluge-web --fork
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch $LOCKFILE
        echo
        return $RETVAL
}

stop() {
        echo -n "Shutting down $prog: "
        pkill deluge
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
        echo
        return $RETVAL
}

status() {
        echo -n "Checking $prog status:"
        echo
        deluged=`ps -ef |grep deluged |grep -v grep |cut -d "/" -f6`
        delugeWeb=`ps -ef |grep deluge-web |grep -v grep |cut -d "0" -f8 |cut -d " " -f2`
        if [ $deluged == "deluged" ]
        then
          echo "The deluged service is running"
        else
          echo "The deluged service is not running"
        fi
        if [ $delugeWeb == "deluge-web" ]
        then
          echo "The deluge web service is running"
        else
          echo "The deluge web service is not running"
        fi
        RETVAL=$?
        return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
